### ISSUE TITLE
Error with PSR-0 fileloading

### ISSUE THREAD

**Issue by OleMchls** [beberlei/WhitewashingLogglyBundle#3]
When you just follow the instructions in the readme, you get an error: "The autoloader expected class "Whitewashing\LogglyBundle\WhitewashingLogglyBundle" to be defined in file "[...]/vendor/bundles/Whitewashing/LogglyBundle/WhitewashingLogglyBundle.php". The file was found but the class was not in it, the class name or namespace probably has a typo."

This is cuased by the Bundle subnamespace, Whitewashing\Bundle...* , this Bundle namespace is not used anywhere else, so there are some smaller adjustments needed, in the documentation, or in the namespaces.

Love,

**Comment by beberlei** [comment]
Why did you close the issue?

**Comment by OleMchls** [comment]
I opened up a new one including the fix ;)

On Mon, May 7, 2012 at 12:36 PM, Benjamin Eberlei <
reply@reply.github.com
